### ISSUE TITLE
Знакомство с GitHub

### ISSUE THREAD

**Issue by proff1337q** [proff1337q/KoreshReportSystem#2]
- клонировать репозиторий в Visual Studio;
- создать отдельную локальную ветку для своей деятельности (koresh);
- изменить значение Title для MainWindow на любое;
- зафиксировать изменения - сделать commit с номером задачи (пример: `#2 Изменен заголовок окна MainWindow`);
- сделать push ветки в репозиторий.

**Comment by AlexeyKoreshkov** [comment]
клонировать репозиторий в Visual Studio - done;
создать отдельную локальную ветку для своей деятельности (koresh) - done;
изменить значение Title для MainWindow на любое - done (изменено на "test 2.1");
зафиксировать изменения - сделать commit с номером задачи (пример: #2 Изменен заголовок окна MainWindow) - done;
сделать push ветки в репозиторий - done.
